sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
sculpin_twig:
    view_paths:
        ['_views', '_layouts', '_partials', '_includes', 'assets/js']
sculpin_twig:
    extensions:
        ['', 'twig', 'html', 'html.twig', 'twig.html', 'js']