sculpin_content_types:
    postsfr:
        type: path
        path: _blog_post_fr
        singular_name: postfr
        layout: postfr
        enabled: true
        permalink: /fr/blog/:year/:month/:day/:filename/
        taxonomies:
            - tags
            - categories
    postsen:
        type: path
        path: _blog_post_en
        singular_name: posten
        layout: posten
        enabled: true
        permalink: /en/blog/:year/:month/:day/:filename/
        taxonomies:
            - tags
            - categories
sculpin_twig:
    view_paths:
        ['_views', '_layouts', '_partials', '_includes', 'assets/js']
sculpin_twig:
    extensions:
        ['', 'twig', 'html', 'html.twig', 'twig.html', 'js']
sculpin:
    ignore: ["**/*~"]
